version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node

    steps:
      - checkout

      - run:
          name: Dependencia
          command: echo Hola Mundo

      - run:
          name: Compilar el sitio
          command: echo Hola Mundo

